export const INCREMENT_ACTION = 'INCREMENT_ACTION';
export const UPDATE_TEXT_ACTION = 'UPDATE_TEXT_ACTION';

export const DATA_FETCH = 'DATA_FETCH';
export const DATA_FETCH_SUCCESS = 'DATA_FETCH_SUCCESS';
export const DATA_FETCH_FAILED = 'DATA_FETCH_FAILED';
